#!/usr/bin/env bash

pushd hopper

rm -rf build

FLASH_ATTENTION_DISABLE_BACKWARD="TRUE" \
    FLASH_ATTENTION_DISABLE_SPLIT=TRUE \
    FLASH_ATTENTION_DISABLE_PAGEDKV=TRUE \
    FLASH_ATTENTION_DISABLE_APPENDKV=TRUE \
    FLASH_ATTENTION_DISABLE_LOCAL=TRUE \
    FLASH_ATTENTION_DISABLE_SOFTCAP=TRUE \
    FLASH_ATTENTION_DISABLE_PACKGQA=TRUE \
    FLASH_ATTENTION_DISABLE_FP8=TRUE \
    FLASH_ATTENTION_DISABLE_VARLEN=TRUE \
    FLASH_ATTENTION_DISABLE_CLUSTER=TRUE \
    FLASH_ATTENTION_DISABLE_HDIM64=TRUE \
    FLASH_ATTENTION_DISABLE_HDIM96=TRUE \
    FLASH_ATTENTION_DISABLE_HDIM192=TRUE \
    FLASH_ATTENTION_DISABLE_HDIM256=TRUE \
    FLASH_ATTENTION_FORCE_BUILD=TRUE \
    NUM_WORKERS=8 python setup.py install

popd
